/**
 * 分析結果からActionsシートにアクション一覧を書き込む
 */
function writeActionsToSheet(analysis, date) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = getOrCreateSheet(ss, 'Actions');

  const headers = [
    'Date',
    'ID',
    'Priority',
    'Category',
    'Title',
    'Description',
    'Impact',
    'Files',
    'Approved',
    'Status',
    'GitHub Issue',
    'PR URL',
    'Claude Code Prompt' // 非表示列
  ];

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]).setFontWeight('bold');
    // Claude Code Prompt列を非表示にする
    sheet.hideColumns(13);
    // Approved列にチェックボックスを設定するため幅調整
    sheet.setColumnWidth(9, 80);
  }

  if (!analysis || !analysis.actions) return;

  const startRow = sheet.getLastRow() + 1;

  analysis.actions.forEach((action, i) => {
    const row = [
      date,
      action.id || `action-${date}-${i}`,
      action.priority || 'medium',
      action.category || 'content',
      action.title,
      action.description,
      action.estimated_impact || '',
      (action.files_affected || []).join(', '),
      false, // Approved（チェックボックス）
      'pending', // Status
      '', // GitHub Issue URL
      '', // PR URL
      action.claude_code_prompt || '' // 非表示
    ];

    sheet.getRange(startRow + i, 1, 1, row.length).setValues([row]);
  });

  // Approved列にチェックボックスを挿入
  const numActions = analysis.actions.length;
  if (numActions > 0) {
    sheet.getRange(startRow, 9, numActions, 1).insertCheckboxes();
  }

  // 条件付き書式（優先度に応じた色分け）
  applyPriorityFormatting(sheet, startRow, numActions);
}

/**
 * 優先度に応じた条件付き書式を適用
 */
function applyPriorityFormatting(sheet, startRow, count) {
  for (let i = 0; i < count; i++) {
    const row = startRow + i;
    const priority = sheet.getRange(row, 3).getValue();
    const range = sheet.getRange(row, 1, 1, 12);

    if (priority === 'high') {
      range.setBackground('#FFF2F0'); // 薄い赤
    } else if (priority === 'medium') {
      range.setBackground('#FFFBE6'); // 薄い黄
    } else {
      range.setBackground('#F6FFED'); // 薄い緑
    }
  }
}

/**
 * 承認済みアクションのGitHub Issueを作成する
 * Google Sheetsのカスタムメニューから実行される
 */
function executeApprovedActions() {
  const config = getConfig();
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName('Actions');

  if (!sheet) {
    SpreadsheetApp.getUi().alert('Actionsシートが見つかりません');
    return;
  }

  const data = sheet.getDataRange().getValues();
  let createdCount = 0;

  for (let i = 1; i < data.length; i++) {
    const approved = data[i][8]; // Approved列
    const status = data[i][9]; // Status列
    const issueUrl = data[i][10]; // GitHub Issue列

    // 承認済み かつ まだIssue未作成のもの
    if (approved === true && status === 'pending' && !issueUrl) {
      const actionId = data[i][1];
      const title = data[i][4];
      const description = data[i][5];
      const category = data[i][3];
      const claudePrompt = data[i][12]; // Claude Code Prompt
      const files = data[i][7];

      // GitHub Issueを作成
      const issue = createGitHubIssue(config, {
        title: `[SEO Auto] ${title}`,
        body: buildIssueBody(actionId, description, claudePrompt, files),
        labels: ['seo-auto-action', category]
      });

      if (issue) {
        // シートを更新
        sheet.getRange(i + 1, 10).setValue('issue-created'); // Status
        sheet.getRange(i + 1, 11).setValue(issue.html_url); // GitHub Issue URL
        createdCount++;
      }
    }
  }

  if (createdCount > 0) {
    SpreadsheetApp.getUi().alert(
      `${createdCount}件のGitHub Issueを作成しました。\n` +
        `Claude Codeが自動的に実装を開始します。`
    );
  } else {
    SpreadsheetApp.getUi().alert('承認済みの未処理アクションはありません。');
  }
}

/**
 * GitHub Issueの本文を構築
 */
function buildIssueBody(actionId, description, claudePrompt, files) {
  return `## Action ID: ${actionId}

### Description
${description}

### Files Affected
${files}

### Claude Code Instructions

<claude-code-prompt>
${claudePrompt}

Additional instructions:
- Create a new branch from main named: seo/${actionId}
- Make the minimum changes necessary
- Run \`npm run build\` to verify the build passes
- Commit with a descriptive message
- Create a PR back to main with a clear description of changes
- Do NOT merge the PR — leave it for human review
</claude-code-prompt>

---
*This issue was auto-generated by the SEO pipeline. Approved by the site owner.*`;
}

/**
 * GitHub APIでIssueを作成
 */
function createGitHubIssue(config, issueData) {
  const token = config.GITHUB_TOKEN;
  const repo = config.GITHUB_REPO;

  if (!token || !repo) {
    Logger.log('GitHub設定が不完全です');
    return null;
  }

  try {
    const response = UrlFetchApp.fetch(
      `https://api.github.com/repos/${repo}/issues`,
      {
        method: 'post',
        contentType: 'application/json',
        headers: {
          Authorization: `token ${token}`,
          Accept: 'application/vnd.github.v3+json'
        },
        payload: JSON.stringify({
          title: issueData.title,
          body: issueData.body,
          labels: issueData.labels
        }),
        muteHttpExceptions: true
      }
    );

    const result = JSON.parse(response.getContentText());

    if (result.html_url) {
      Logger.log(`GitHub Issue作成成功: ${result.html_url}`);
      return result;
    } else {
      Logger.log(`GitHub Issue作成エラー: ${JSON.stringify(result)}`);
      return null;
    }
  } catch (e) {
    Logger.log(`GitHub API Error: ${e.message}`);
    return null;
  }
}
